spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/minhhoang199/cloud-config-server

server:
  port: 9196

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: true
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
